name: CI_PRE_DEPLOY

on:
  push:
    branches: [workflow-setup3]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Run a one-line script
      run: echo Hello, world!

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: yarn install

    - name: Test linting
      run: yarn run lint:fix


    - name: Create build
      run: yarn run build
    - name: Deploy Production on heroku.
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "babitz-backend"
          heroku_email: "jagdeepak009@gmail.com"
