name: CI_CD_HEROKU

on:
  push:
    branches: [add-workflow-setup]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Test linting
      run: yarn run lint

    - name: Run Coverage
      run: yarn run test:coverage

    - name: generate Coverage report
      run: yarn run coverage:ci

    - name: Check coverate threshold.
      uses: VGVentures/very-good-coverage@v1.1.1
      with:
        path: "./coverage/lcov.info"
        min_coverage: 50
    - name: Create build
      run: yarn run build

    - name: Deploy Production on heroku.
    - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "babitz-backend"
          heroku_email: "jagdeepak009@gmail.com"



