name: CI_PRE_DEPLOY

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Test linting
      run: npm run lint
      run: npm run test:coverage

    - name: Create build
      run: npm run build
    - name: Deploy Production on heroku.
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "babitz-backend"
          heroku_email: "jagdeepak009@gmail.com"





