name: CI_CD

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Run a one-line script
      run: echo Hello, world!

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Test linting
      run: yarn run lint:test

    - name: Run Unit Tests
      run: yarn run test

    - name: Run Coverage
      run: npm run test:coverage

    - name: generate Coverage report
      run: npm run coverage:ci

    - name: Check coverage threshold.
      uses: VGVentures/very-good-coverage@v1.1.1
      with:
        path: "./.nyc_coverage/lcov.info"
        min_coverage: 30

    - name: Deploy Production on heroku.
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "babitz-backend"
          heroku_email: "jagdeepak009@gmail.com"
