name: CI_CD

on:
  push:
    branches: [main]
  workflow_dispatch:
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  S3_ACCESSKEYID: ${{ secrets.S3_ACCESSKEYID }}
  S3_SECRETACCESSKEY: ${{ secrets.S3_SECRETACCESSKEY }}
  S3_REGION: ${{ secrets.S3_REGION }}
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
  FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
  RAZORPAY_KEY_ID: ${{ secrets.RAZORPAY_KEY_ID }}
  RAZORPAY_KEY_SECRET:  ${{ secrets.RAZORPAY_KEY_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Run a one-line script
      run: echo Hello, world!

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Test linting
      run: yarn run lint

    - name: Run Unit Tests
      run: yarn run test

    - name: Run Coverage
      run: yarn run test:coverage

    - name: generate Coverage report
      run: yarn run coverage:ci

    - name: Check coverage threshold.
      uses: VGVentures/very-good-coverage@v1.1.1
      with:
        path: "./.nyc_coverage/lcov.info"
        min_coverage: 30

    - name: Deploy Production on heroku.
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "babitz-backend"
          heroku_email: "jagdeepak009@gmail.com"
